app:
  name: order-service
  env: local

server:
  grpc_addr: ":50051"
  shutdown_timeout: 10s

logger:
  level: debug
  json: true

db:
  dsn: ${DB_DSN}

kafka:
  brokers: ["kafka:9092"]
  topic_order_created: "order.created"
  group_id: "notification-service"

redis:
  addr: "redis:6379"
  password: ""
  db: 0